site_name: MathWallet NFT Wiki
site_description: In Math We Trust!
site_author: MathWallet

site_url: https://mathwallet.github.io/nft_docs
repo_url: https://github.com/mathwallet/nft_docs

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathWallet

nav:
  - Home: index.md
  - English:
    - 'Preface': en/preface.md
    - 'Basics':
      - 'What is NFT？': 'en/basics/What is NFT？.md'
      - 'NFT Dictionary': 'en/basics/NFT dictionary.md'
      - 'NFT Origin': 'en/basics/NFT Origin.md'
      - 'NFT Standard': 'en/basics/NFT Standard.md'
      - 'NFT Characteristics': 'en/basics/NFT Characteristics.md'
      - 'Delete or burn NFT': 'en/basics/Delete or burn NFT.md'
      - 'NFT Functions': 'en/basics/NFT Functions.md'
      - 'NFT in DeFi': 'en/basics/NFT in DeFi.md'
      - 'NFT assets vs Internet files': 'en/basics/NFT assets vs Internet files.md'
      - 'NFT security': 'en/basics/NFT security.md'
    - 'NFT Collector Guide':
      - 'How to collect an NFT': 'en/nft_collector_guide/How to collect an NFT.md'
      - 'How to buy an NFT': 'en/nft_collector_guide/How to buy an NFT.md'
      - 'How to sell an NFT': 'en/nft_collector_guide/How to sell an NFT.md'
      - 'NFT advanced gameplay': 'en/nft_collector_guide/NFT advanced gameplay.md'
      - 'How to evaluate the value of NFT': 'en/nft_collector_guide/How to evaluate the value of NFT.md'
      - 'NFT Data Browser': 'en/nft_collector_guide/NFT Data Browser.md'
      - 'NFT well-known collector': 'en/nft_collector_guide/NFT well-known collector.md'
      - 'The ten most expensive NFTs in history': 'en/nft_collector_guide/The ten most expensive NFTs in history.md'
    - 'NFT Creator Guide':
      - 'How to choose NFT publishing platform': 'en/nft_creator_guide/How to choose NFT publishing platform.md'
      - 'How to create your own NFT': 'en/nft_creator_guide/How to create your own NFT.md'
      - 'How to sell your own NFT': 'en/nft_creator_guide/How to sell your own NFT.md'
      - 'The relationship between NFT and copyright': 'en/nft_creator_guide/The relationship between NFT and copyright.md'
    - 'NFT Developer Guide':
      - 'Create NFT smart contract': 'en/nft_developer_guide/Create NFT smart contract.md'
      - 'NFT Metadata Standard': 'en/nft_developer_guide/NFT Metadata Standard.md'
      - 'NFT Metadata Storage': 'en/nft_developer_guide/NFT Metadata Storage.md'
    - 'NFT Projects':
      - 'CryptoPunks': 'en/nft_projects/CryptoPunks.md'
      - 'CryptoKitties': 'en/nft_projects/CryptoKitties.md'
      - 'Decentraland': 'en/nft_projects/Decentraland.md'
      - 'CryptoVoxels': 'en/nft_projects/CryptoVoxels.md'
      - 'AART': 'en/nft_projects/AART.md'
      - 'Flow': 'en/nft_projects/Flow.md'
      - 'Twinci': 'en/nft_projects/Twinci.md'
      - 'CryptoArt.Ai': 'en/nft_projects/CryptoArt.Ai.md'
      - 'Re-NFT': 'en/nft_projects/Re-NFT.md'
      - 'RMRK': 'en/nft_projects/RMRK.md'
      - 'KodaDot': 'en/nft_projects/KodaDot.md'
      - 'Cybertino': 'en/nft_projects/Cybertino.md'
      - 'MyNFT': 'en/nft_projects/MyNFT.md'
      - 'Unique': 'en/nft_projects/Unique.md'
    - 'Contact Us': 'en/contact_us.md'
  - 中文:
    - '前言': cn/preface.md
    - '基础知识':
      - '什么是NFT': 'cn/basics/What is NFT？.md'
      - 'NFT词典': 'cn/basics/NFT dictionary.md'
      - 'NFT起源': 'cn/basics/NFT Origin.md'
      - 'NFT标准': 'cn/basics/NFT Standard.md'
      - 'NFT的特性': 'cn/basics/NFT Characteristics.md'
      - 'NFT的销毁': 'cn/basics/Delete or burn NFT.md'
      - 'NFT的用途': 'cn/basics/NFT Functions.md'
      - 'NFT在Defi中的应用': 'cn/basics/NFT in DeFi.md'
      - 'NFT资产与互联网文件的区别': 'cn/basics/NFT assets vs Internet files.md'
      - 'NFT安全': 'cn/basics/NFT security.md'
    - 'NFT藏家指南':
      - '如何收藏一枚NFT': 'cn/nft_collector_guide/How to collect an NFT.md'
      - '如何购买一枚NFT': 'cn/nft_collector_guide/How to buy an NFT.md'
      - '如何出售一枚NFT': 'cn/nft_collector_guide/How to sell an NFT.md'
      - 'NFT的高级玩法': 'cn/nft_collector_guide/NFT advanced gameplay.md'
      - '如何评估NFT的价值': 'cn/nft_collector_guide/How to evaluate the value of NFT.md'
      - 'NFT相关数据网站': 'cn/nft_collector_guide/NFT Data Browser.md'
      - 'NFT知名收藏家': 'cn/nft_collector_guide/NFT well-known collector.md'
      - '史上十大最贵NFT': 'cn/nft_collector_guide/The ten most expensive NFTs in history.md'
    - 'NFT创作者指南':
      - '如何选择NFT发布平台': 'cn/nft_creator_guide/How to choose NFT publishing platform.md'
      - '如何创建自己的NFT': 'cn/nft_creator_guide/How to create your own NFT.md'
      - '如何销售自己的NFT': 'cn/nft_creator_guide/How to sell your own NFT.md'
      - 'NFT和版权的关系': 'cn/nft_creator_guide/The relationship between NFT and copyright.md'
    - 'NFT开发者指南':
      - '创建NFT智能合约': 'cn/nft_developer_guide/Create NFT smart contract.md'
      - 'NFT元数据标准': cn/nft_developer_guide/NFT Metadata Standard.md'
      - 'NFT元数据存储': 'cn/nft_developer_guide/NFT Metadata Storage.md'
    - 'NFT项目':
      - 'CryptoPunks': 'cn/nft_projects/CryptoPunks.md'
      - 'Cryptokitties': 'en/nft_projects/Cryptokitties.md'
      - 'Opensea': 'en/nft_projects/Opensea.md'
      - 'Binance NFT Market': 'en/nft_projects/Binance NFT Market.md'
      - 'Decentraland': 'en/nft_projects/Decentraland.md'
      - 'CryptoVoxels': 'en/nft_projects/CryptoVoxels.md'
      - 'NBA Top Shots': 'en/nft_projects/NBA Top Shots.md'
      - 'Rarible': 'en/nft_projects/Rarible.md'
      - 'Nifty Gateway': 'en/nft_projects/Nifty Gateway.md'
      - 'BakerySwap': 'en/nft_projects/BakerySwap.md'
      - 'DEGO.Finance': 'en/nft_projects/DEGO.Finance.md'
      - 'MakersPlace': 'en/nft_projects/MakersPlace.md'
      - 'Flow': 'cn/nft_projects/Flow.md'
      - 'SuperRare': 'cn/nft_projects/SuperRare.md'
      - 'VIV3': 'cn/nft_projects/VIV3.md'
      - 'Enjin': 'cn/nft_projects/Enjin.md'
      - 'AART': 'cn/nft_projects/AART.md'
      - 'Cybertino': 'cn/nft_projects/Cybertino.md'
      - 'FM Gallery': 'cn/nft_projects/FM Gallery.md'
      - 'Treasureland': 'cn/nft_projects/Treasureland.md'
      - 'Bit.Country': 'cn/nft_projects/Bit.Country.md'
      - 'KodaDot': 'cn/nft_projects/KodaDot.md'
      - 'RMRK': 'cn/nft_projects/RMRK.md'
      - 'PolkaPets': 'cn/nft_projects/PolkaPets.md'
      - 'Seascape Network': 'cn/nft_projects/Seascape Network.md'
      - 'MyNFT': 'cn/nft_projects/MyNFT.md'
      - 'Twinci': 'cn/nft_projects/Twinci.md'
      - 'Unique': 'cn/nft_projects/Unique.md'
      - 'CryptoArt.Ai': 'cn/nft_projects/CryptoArt.Ai.md'
      - 'BCA Network': 'cn/nft_projects/BCA Network.md'
      - 'Top Bidder': 'cn/nft_projects/Top Bidder.md'
      - 'ATTA': 'cn/nft_projects/ATTA.md'
      - 'Re-NFT': 'cn/nft_projects/Re-NFT.md'
      
      
      
      
      
    - '联系我们': 'cn/contact_us.md'

plugins:
  - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: 'https://github.com/mathwallet'
    # - icon: fontawesome/brands/twitter-alt
    #   link: 'https://twitter.com/mathwallet'
